<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Surefire suite]" verbose="0">
  <test thread-count="5" name="Surefire test(failed)" verbose="0">
    <classes>
      <class name="rahulshettyacademy.Test.SubmitOrderTest">
        <methods>
          <include name="tearDown"/>
          <include name="submitOrder"/>
          <include name="launchApplication"/>
          <include name="OrderHistory"/>
        </methods>
      </class> <!-- rahulshettyacademy.Test.SubmitOrderTest -->
      <class name="rahulshettyacademy.Test.ErrorValidationsTest">
        <methods>
          <include name="ProductErrorValidation"/>
          <include name="tearDown"/>
          <include name="loginErrorValidation"/>
          <include name="launchApplication"/>
        </methods>
      </class> <!-- rahulshettyacademy.Test.ErrorValidationsTest -->
      <class name="Cucumber.TestNGTestRunner">
        <methods>
          <include name="setUpClass"/>
          <include name="tearDownClass"/>
          <include name="runScenario" invocation-numbers="0 1"/>
        </methods>
      </class> <!-- Cucumber.TestNGTestRunner -->
    </classes>
  </test> <!-- Surefire test(failed) -->
</suite> <!-- Failed suite [Surefire suite] -->
